# Generated by Django 3.1.3 on 2024-05-13 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('capital', models.CharField(max_length=255)),
                ('population', models.IntegerField()),
                ('language', models.CharField(max_length=255)),
            ],
        ),
    ]
